from enum import Enum


class MODALITY(Enum):
    CORRIDA = "CORRIDA"
    CAMINHADA = "CAMINHADA"
    CICLISMO = "CICLISMO"
    NATACAO = "NATACAO"
    ACADEMIA = "ACADEMIA"
    OUTRO = "OUTRO"
    YOGA = "YOGA"
    FUTEBOL = "FUTEBOL"
    BASQUETE = "BASQUETE"
    