from enum import Enum

class URINE_COLOR(Enum):
    TRANSLUCIDO = "TRANSLUCIDO"
    AMARELO_CLARO = "AMARELO_CLARO"
    AMARELO = "AMARELO"
    AMARELO_ESCURO = "AMARELO_ESCURO"
    LARANJA = "LARANJA"
    VERDE = "VERDE"
    VERDE_ESCURO = "VERDE_ESCURO"