from enum import Enum

class URINE_COLOR(Enum):
    TRANSLUCIDO = "TRANSLUCIDO"
    AMARELO_CLARO = "AMARELO_CLARO"
    AMARELO = "AMARELO"
    AMARELO_ESCURO = "AMARELO_ESCURO"
    LARANJA = "LARANJA"
    MARROM = "MARROM"